"""deleted type column from operations table

Revision ID: 23b2f5193be9
Revises: fe9047ef7c82
Create Date: 2026-03-09 13:32:44.535267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '23b2f5193be9'
down_revision: Union[str, Sequence[str], None] = 'fe9047ef7c82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('operations', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operations', sa.Column('type', postgresql.ENUM('INCOME', 'EXPENSE', 'TRANSFER', name='operationtype'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
