"""deleted account_id column from chains table

Revision ID: 2955f45bcaf5
Revises: f71592235986
Create Date: 2026-04-03 11:25:37.326566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2955f45bcaf5'
down_revision: Union[str, Sequence[str], None] = 'f71592235986'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('chains_account_id_fkey'), 'chains', type_='foreignkey')
    op.drop_column('chains', 'account_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chains', sa.Column('account_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('chains_account_id_fkey'), 'chains', 'accounts', ['account_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
