"""Deleted amount field from chains table

Revision ID: 6c78ac14a550
Revises: e5b25a49d4f6
Create Date: 2026-03-19 14:50:07.886609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c78ac14a550'
down_revision: Union[str, Sequence[str], None] = 'e5b25a49d4f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chains', 'amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chains', sa.Column('amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
