"""added related_operation_id column to operations table for transfers

Revision ID: 7dd1a85924e5
Revises: 23b2f5193be9
Create Date: 2026-03-10 00:02:27.354582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7dd1a85924e5'
down_revision: Union[str, Sequence[str], None] = '23b2f5193be9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operations', sa.Column('related_operation_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'operations', 'operations', ['related_operation_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'operations', type_='foreignkey')
    op.drop_column('operations', 'related_operation_id')
    # ### end Alembic commands ###
