"""Deleted unneсessary index and added necessary indexes

Revision ID: 9232d9362c7f
Revises: 9ae95eda27e5
Create Date: 2026-03-13 16:32:14.041760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9232d9362c7f'
down_revision: Union[str, Sequence[str], None] = '9ae95eda27e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_user_is_active', 'accounts', ['user_id', 'is_active'], unique=False)
    op.drop_index(op.f('idx_user_id_id'), table_name='operations')
    op.create_index('idx_account_date', 'operations', ['account_id', 'date'], unique=False)
    op.create_index('idx_category_date', 'operations', ['category_id', 'date'], unique=False)
    op.create_index('idx_user_date', 'operations', ['user_id', 'date'], unique=False)
    op.create_index('idx_user_name_type', 'user_categories', ['user_id', 'name', 'type'], unique=False)
    op.create_index('idx_user_type_is_active', 'user_categories', ['user_id', 'type', 'is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_type_is_active', table_name='user_categories')
    op.drop_index('idx_user_name_type', table_name='user_categories')
    op.drop_index('idx_user_date', table_name='operations')
    op.drop_index('idx_category_date', table_name='operations')
    op.drop_index('idx_account_date', table_name='operations')
    op.create_index(op.f('idx_user_id_id'), 'operations', ['user_id', 'id'], unique=False)
    op.drop_index('idx_user_is_active', table_name='accounts')
    # ### end Alembic commands ###
