"""added deletable column to user_categories table

Revision ID: 9ae95eda27e5
Revises: 7dd1a85924e5
Create Date: 2026-03-10 00:46:19.611700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ae95eda27e5'
down_revision: Union[str, Sequence[str], None] = '7dd1a85924e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_categories', sa.Column('deletable', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_categories', 'deletable')
    # ### end Alembic commands ###
