"""Deleted uq_name_user_id_is_active unique constraint and add partial index in accounts table

Revision ID: adc0bc7399c2
Revises: 6c78ac14a550
Create Date: 2026-03-24 22:30:36.316169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adc0bc7399c2'
down_revision: Union[str, Sequence[str], None] = '6c78ac14a550'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_accounts_name_user_is_active'), 'accounts', type_='unique')
    op.create_index('uq_active_accounts_name_type_curr', 'accounts', ['user_id', 'name', 'type', 'currency'], unique=True, postgresql_where=sa.text('is_active = true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_active_accounts_name_type_curr', table_name='accounts', postgresql_where=sa.text('is_active = true'))
    op.create_unique_constraint(op.f('uq_accounts_name_user_is_active'), 'accounts', ['name', 'user_id', 'is_active'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
