"""Added users is_admin, is_staff fields, added system_categories table, added user_categories table

Revision ID: d447a0b49edb
Revises: f8b0615b660d
Create Date: 2026-03-02 17:47:44.393603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd447a0b49edb'
down_revision: Union[str, Sequence[str], None] = 'f8b0615b660d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sys_categories',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('INCOME', 'EXPENSE', 'TRANSFER', name='operationtype'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_categories',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('INCOME', 'EXPENSE', 'TRANSFER', name='operationtype'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'user_id', 'type', name='uq_user_categories_name_user_type')
    )
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), server_default='FALSE', nullable=False))
    op.add_column('users', sa.Column('is_staff', sa.Boolean(), server_default='FALSE', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_staff')
    op.drop_column('users', 'is_admin')
    op.drop_table('user_categories')
    op.drop_table('sys_categories')
    # ### end Alembic commands ###
