"""Make categories personal

Revision ID: f11ca4b4aa0f
Revises: 01a28753525f
Create Date: 2025-12-11 01:19:41.355201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f11ca4b4aa0f'
down_revision: Union[str, Sequence[str], None] = '01a28753525f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('expense_category_id_fkey'), 'expense', type_='foreignkey')
    op.drop_constraint(op.f('expense_user_id_fkey'), 'expense', type_='foreignkey')
    op.create_foreign_key(None, 'expense', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'expense', 'expensecategory', ['category_id'], ['id'], ondelete='CASCADE')
    op.add_column('expensecategory', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_expensecategory_name'), table_name='expensecategory')
    op.create_index(op.f('ix_expensecategory_name'), 'expensecategory', ['name'], unique=False)
    op.create_unique_constraint('uq_expensecategory_name_user', 'expensecategory', ['name', 'user_id'])
    op.create_foreign_key(None, 'expensecategory', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('income_user_id_fkey'), 'income', type_='foreignkey')
    op.drop_constraint(op.f('income_category_id_fkey'), 'income', type_='foreignkey')
    op.create_foreign_key(None, 'income', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'income', 'incomecategory', ['category_id'], ['id'], ondelete='CASCADE')
    op.add_column('incomecategory', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_incomecategory_name'), table_name='incomecategory')
    op.create_index(op.f('ix_incomecategory_name'), 'incomecategory', ['name'], unique=False)
    op.create_unique_constraint('uq_incomecategory_name_user', 'incomecategory', ['name', 'user_id'])
    op.create_foreign_key(None, 'incomecategory', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'incomecategory', type_='foreignkey')
    op.drop_constraint('uq_incomecategory_name_user', 'incomecategory', type_='unique')
    op.drop_index(op.f('ix_incomecategory_name'), table_name='incomecategory')
    op.create_index(op.f('ix_incomecategory_name'), 'incomecategory', ['name'], unique=True)
    op.drop_column('incomecategory', 'user_id')
    op.drop_constraint(None, 'income', type_='foreignkey')
    op.drop_constraint(None, 'income', type_='foreignkey')
    op.create_foreign_key(op.f('income_category_id_fkey'), 'income', 'incomecategory', ['category_id'], ['id'])
    op.create_foreign_key(op.f('income_user_id_fkey'), 'income', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'expensecategory', type_='foreignkey')
    op.drop_constraint('uq_expensecategory_name_user', 'expensecategory', type_='unique')
    op.drop_index(op.f('ix_expensecategory_name'), table_name='expensecategory')
    op.create_index(op.f('ix_expensecategory_name'), 'expensecategory', ['name'], unique=True)
    op.drop_column('expensecategory', 'user_id')
    op.drop_constraint(None, 'expense', type_='foreignkey')
    op.drop_constraint(None, 'expense', type_='foreignkey')
    op.create_foreign_key(op.f('expense_user_id_fkey'), 'expense', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('expense_category_id_fkey'), 'expense', 'expensecategory', ['category_id'], ['id'])
    # ### end Alembic commands ###
