"""added amount and operations_count columns to chains table

Revision ID: f71592235986
Revises: adc0bc7399c2
Create Date: 2026-03-26 21:06:32.830025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f71592235986'
down_revision: Union[str, Sequence[str], None] = 'adc0bc7399c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chains', sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False))
    op.add_column('chains', sa.Column('operations_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chains', 'operations_count')
    op.drop_column('chains', 'amount')
    # ### end Alembic commands ###
