"""added indexes to chains table

Revision ID: f8d4bfe81d18
Revises: feaf76cc3567
Create Date: 2026-04-25 13:34:10.026455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8d4bfe81d18'
down_revision: Union[str, Sequence[str], None] = 'feaf76cc3567'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_chains_category_date', 'chains', ['category_id', 'date'], unique=False)
    op.create_index('idx_chains_user_date', 'chains', ['user_id', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_chains_user_date', table_name='chains')
    op.drop_index('idx_chains_category_date', table_name='chains')
    # ### end Alembic commands ###
