"""changed ondelete from cascade to set null on related_operation_id column in operations

Revision ID: feaf76cc3567
Revises: 2955f45bcaf5
Create Date: 2026-04-24 18:50:34.629166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'feaf76cc3567'
down_revision: Union[str, Sequence[str], None] = '2955f45bcaf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('operations_related_operation_id_fkey'), 'operations', type_='foreignkey')
    op.create_foreign_key(None, 'operations', 'operations', ['related_operation_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'operations', type_='foreignkey')
    op.create_foreign_key(op.f('operations_related_operation_id_fkey'), 'operations', 'operations', ['related_operation_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
